#!/usr/bin/env python3
import json
from pathlib import Path
from types import SimpleNamespace

# ══════════════════════════════════════════════════════════════════════════════
#  EDIT HERE — define your dark and light palettes
# ══════════════════════════════════════════════════════════════════════════════

dark = SimpleNamespace(
    # ── Base
    background="#24283b",
    foreground="#c0caf5",
    cursor="#dad1e3",
    selection_bg="#c2a9db",
    selection_fg="#c2a9db",
    # ── ANSI 0-7
    black="#1d202f",
    red="#f7768e",
    green="#9ece6a",
    yellow="#e0af68",
    blue="#7aa2f7",
    magenta="#bb9af7",
    cyan="#7dcfff",
    white="#a9b1d6",
    # ── ANSI 8-15 (bright)
    bright_black="#414868",
    bright_red="#f7768e",
    bright_green="#9ece6a",
    bright_yellow="#e0af68",
    bright_blue="#7aa2f7",
    bright_magenta="#bb9af7",
    bright_cyan="#7dcfff",
    bright_white="#c0caf5",
    # ── Syntax (Zed editor only — set to None to inherit from ANSI colors above)
    syn_keyword="#9d7cd8",
    syn_string="#9ece6a",
    syn_comment="#565f89",
    syn_function="#7aa2f7",
    syn_type="#2ac3de",
    syn_constant="#ff9e64",
    syn_number="#ff9e64",
    syn_operator="#89ddff",
    syn_property="#73daca",
    syn_variable="#c0caf5",
    syn_tag="#f7768e",
    syn_attribute="#e0af68",
    syn_punctuation="#89ddff",
)

# ── Theme registry: (filename, zed appearance, palette)
THEMES = [
    ("user-theme", "dark", dark),
]


def _mix(a, b, t):
    """Interpolate between two hex colors. t=0 → a, t=1 → b."""
    ca = [int(a.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4)]
    cb = [int(b.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4)]
    return "#{:02x}{:02x}{:02x}".format(
        *[round(ca[i] + (cb[i] - ca[i]) * t) for i in range(3)]
    )


def _sx(p, attr, fallback):
    return getattr(p, attr, None) or fallback


def ghostty(name, p):
    return (
        "\n".join(
            [
                f"# {name} — generated by colors.py",
                "",
                f"background           = {p.background}",
                f"foreground           = {p.foreground}",
                f"cursor-color         = {p.cursor}",
                f"selection-background = {p.selection_bg}",
                f"selection-foreground = {p.selection_fg}",
                "",
                "# ANSI palette",
                f"palette = 0={p.black}",
                f"palette = 1={p.red}",
                f"palette = 2={p.green}",
                f"palette = 3={p.yellow}",
                f"palette = 4={p.blue}",
                f"palette = 5={p.magenta}",
                f"palette = 6={p.cyan}",
                f"palette = 7={p.white}",
                f"palette = 8={p.bright_black}",
                f"palette = 9={p.bright_red}",
                f"palette = 10={p.bright_green}",
                f"palette = 11={p.bright_yellow}",
                f"palette = 12={p.bright_blue}",
                f"palette = 13={p.bright_magenta}",
                f"palette = 14={p.bright_cyan}",
                f"palette = 15={p.bright_white}",
            ]
        )
        + "\n"
    )


def zed(name, appearance, p):
    dark_mode = appearance == "dark"
    bg, fg = p.background, p.foreground
    hi = "#ffffff" if dark_mode else "#000000"
    surface = _mix(bg, hi, 0.05)
    elevated = _mix(bg, hi, 0.08)
    border = _mix(bg, hi, 0.12)
    subtle = _mix(fg, bg, 0.5)

    style = {
        "background": bg,
        "surface.background": surface,
        "elevated_surface.background": elevated,
        "panel.background": surface,
        "status_bar.background": surface,
        "title_bar.background": surface,
        "toolbar.background": bg,
        "tab_bar.background": surface,
        "tab.inactive_background": surface,
        "tab.active_background": bg,
        "drop_target.background": _mix(p.blue, bg, 0.8),
        "border": border,
        "border.variant": border,
        "border.focused": p.blue,
        "border.selected": p.blue,
        "border.transparent": "#00000000",
        "border.disabled": border,
        "text": fg,
        "text.muted": subtle,
        "text.placeholder": subtle,
        "text.disabled": subtle,
        "text.accent": p.blue,
        "element.background": "#00000000",
        "element.hover": _mix(p.blue, bg, 0.9),
        "element.active": _mix(p.blue, bg, 0.8),
        "element.selected": _mix(p.blue, bg, 0.85),
        "element.disabled": border,
        "ghost_element.hover": _mix(fg, bg, 0.08),
        "ghost_element.active": _mix(fg, bg, 0.12),
        "ghost_element.selected": _mix(fg, bg, 0.1),
        "editor.foreground": fg,
        "editor.background": bg,
        "editor.gutter.background": bg,
        "editor.line_number": subtle,
        "editor.active_line_number": fg,
        # "editor.active_line.background": _mix(fg, bg, 0.05),
        "editor.wrap_guide": border,
        "editor.active_wrap_guide": subtle,
        "editor.invisible": border,
        "editor.indent_guide": border,
        "editor.indent_guide_active": subtle,
        "editor.document_highlight.read_background": _mix(p.yellow, bg, 0.85),
        "editor.document_highlight.write_background": _mix(p.yellow, bg, 0.75),
        "search.match_background": _mix(p.yellow, bg, 0.7),
        "search.active_match_background": _mix(p.yellow, bg, 0.5),
        "selection": p.selection_bg,
        "scrollbar.thumb.background": _mix(fg, bg, 0.2),
        "scrollbar.thumb.hover_background": _mix(fg, bg, 0.35),
        "scrollbar.thumb.border": border,
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": border,
        "error": p.red,
        "error.background": _mix(p.red, bg, 0.85),
        "error.border": _mix(p.red, bg, 0.6),
        "warning": p.yellow,
        "warning.background": _mix(p.yellow, bg, 0.85),
        "warning.border": _mix(p.yellow, bg, 0.6),
        "info": p.blue,
        "info.background": _mix(p.blue, bg, 0.85),
        "info.border": _mix(p.blue, bg, 0.6),
        "hint": subtle,
        "hint.background": _mix(fg, bg, 0.08),
        "hint.border": border,
        "success": p.green,
        "success.background": _mix(p.green, bg, 0.85),
        "success.border": _mix(p.green, bg, 0.6),
        "created": p.green,
        "created.background": _mix(p.green, bg, 0.88),
        "created.border": _mix(p.green, bg, 0.7),
        "modified": p.blue,
        "modified.background": _mix(p.blue, bg, 0.88),
        "modified.border": _mix(p.blue, bg, 0.7),
        "deleted": p.red,
        "deleted.background": _mix(p.red, bg, 0.88),
        "deleted.border": _mix(p.red, bg, 0.7),
        "conflict": p.yellow,
        "conflict.background": _mix(p.yellow, bg, 0.88),
        "conflict.border": _mix(p.yellow, bg, 0.7),
        "hidden": subtle,
        "hidden.background": bg,
        "hidden.border": border,
        "ignored": subtle,
        "ignored.background": bg,
        "ignored.border": border,
        "renamed": p.cyan,
        "renamed.background": _mix(p.cyan, bg, 0.88),
        "renamed.border": _mix(p.cyan, bg, 0.7),
        "link_text.hover": p.blue,
        "terminal.background": bg,
        "terminal.foreground": fg,
        "terminal.bright_foreground": p.bright_white,
        "terminal.dim_foreground": subtle,
        "terminal.ansi.black": p.black,
        "terminal.ansi.red": p.red,
        "terminal.ansi.green": p.green,
        "terminal.ansi.yellow": p.yellow,
        "terminal.ansi.blue": p.blue,
        "terminal.ansi.magenta": p.magenta,
        "terminal.ansi.cyan": p.cyan,
        "terminal.ansi.white": p.white,
        "terminal.ansi.bright_black": p.bright_black,
        "terminal.ansi.bright_red": p.bright_red,
        "terminal.ansi.bright_green": p.bright_green,
        "terminal.ansi.bright_yellow": p.bright_yellow,
        "terminal.ansi.bright_blue": p.bright_blue,
        "terminal.ansi.bright_magenta": p.bright_magenta,
        "terminal.ansi.bright_cyan": p.bright_cyan,
        "terminal.ansi.bright_white": p.bright_white,
        "terminal.ansi.dim_black": _mix(p.black, bg, 0.4),
        "terminal.ansi.dim_red": _mix(p.red, bg, 0.4),
        "terminal.ansi.dim_green": _mix(p.green, bg, 0.4),
        "terminal.ansi.dim_yellow": _mix(p.yellow, bg, 0.4),
        "terminal.ansi.dim_blue": _mix(p.blue, bg, 0.4),
        "terminal.ansi.dim_magenta": _mix(p.magenta, bg, 0.4),
        "terminal.ansi.dim_cyan": _mix(p.cyan, bg, 0.4),
        "terminal.ansi.dim_white": _mix(p.white, bg, 0.4),
        "syntax": {
            "keyword": {"color": _sx(p, "syn_keyword", p.red)},
            "keyword.operator": {"color": _sx(p, "syn_operator", fg)},
            "string": {"color": _sx(p, "syn_string", p.green)},
            "string.escape": {"color": _sx(p, "syn_string", p.green)},
            "string.regex": {"color": _sx(p, "syn_string", p.green)},
            "string.special": {"color": _sx(p, "syn_string", p.green)},
            "comment": {
                "color": _sx(p, "syn_comment", p.bright_black),
                "font_style": "italic",
            },
            "comment.doc": {
                "color": _sx(p, "syn_comment", p.bright_black),
                "font_style": "italic",
            },
            "function": {"color": _sx(p, "syn_function", p.blue)},
            "function.builtin": {"color": _sx(p, "syn_function", p.blue)},
            "function.method": {"color": _sx(p, "syn_function", p.blue)},
            "type": {"color": _sx(p, "syn_type", p.yellow)},
            "type.builtin": {"color": _sx(p, "syn_type", p.yellow)},
            "constant": {"color": _sx(p, "syn_constant", p.blue)},
            "constant.builtin": {"color": _sx(p, "syn_constant", p.blue)},
            "number": {"color": _sx(p, "syn_number", p.blue)},
            "boolean": {"color": _sx(p, "syn_constant", p.blue)},
            "operator": {"color": _sx(p, "syn_operator", fg)},
            "property": {"color": _sx(p, "syn_property", p.blue)},
            "variable": {"color": _sx(p, "syn_variable", fg)},
            "variable.special": {"color": _sx(p, "syn_variable", p.magenta)},
            "tag": {"color": _sx(p, "syn_tag", p.red)},
            "attribute": {"color": _sx(p, "syn_attribute", p.yellow)},
            "constructor": {"color": _sx(p, "syn_type", p.yellow)},
            "preproc": {"color": _sx(p, "syn_keyword", p.red)},
            "punctuation": {"color": _sx(p, "syn_punctuation", fg)},
            "punctuation.bracket": {"color": _sx(p, "syn_punctuation", fg)},
            "punctuation.delimiter": {"color": _sx(p, "syn_punctuation", fg)},
            "punctuation.special": {"color": _sx(p, "syn_punctuation", fg)},
            "enum": {"color": _sx(p, "syn_type", p.yellow)},
            "text.literal": {"color": _sx(p, "syn_string", p.green)},
        },
        "players": [
            {"cursor": p.cursor, "background": bg, "selection": p.selection_bg},
            {
                "cursor": p.magenta,
                "background": bg,
                "selection": _mix(p.magenta, bg, 0.8),
            },
            {"cursor": p.green, "background": bg, "selection": _mix(p.green, bg, 0.8)},
            {
                "cursor": p.yellow,
                "background": bg,
                "selection": _mix(p.yellow, bg, 0.8),
            },
            {"cursor": p.cyan, "background": bg, "selection": _mix(p.cyan, bg, 0.8)},
            {"cursor": p.red, "background": bg, "selection": _mix(p.red, bg, 0.8)},
        ],
        "accents": [p.blue, p.magenta, p.green, p.yellow, p.cyan, p.red],
    }

    return {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": name,
        "author": "colors.py",
        "themes": [{"name": name, "appearance": appearance, "style": style}],
    }


def main():
    root = Path(__file__).parent
    (root / "ghostty" / "themes").mkdir(parents=True, exist_ok=True)
    (root / "themes").mkdir(parents=True, exist_ok=True)

    for name, appearance, palette in THEMES:
        (root / "ghostty" / "themes" / name).write_text(ghostty(name, palette))
        (root / "themes" / f"{name}.json").write_text(
            json.dumps(zed(name, appearance, palette), indent=2) + "\n"
        )
        print(f"  {name}")

    print(f"\nGenerated {len(THEMES)} themes.")
    print("Ghostty: Cmd+Shift+,   Zed: automatic")


if __name__ == "__main__":
    main()
